sentences:
  aam:
  - arrived_circle
  - passed_waypt
  - arrival_radius
  - radius_units
  - waypt_id
  apa:
  - ap_status
  - ap_loran
  - xte
  - arrived_circle
  - passed_waypt
  - bearing_to_waypt
  - waypt_id
  apb:
  - ap_status
  - ap_loran
  - xte
  - arrived_circle
  - passed_waypt
  - bearing_origin_to_waypt
  - waypt_id
  - bearing_position_to_waypt
  - hts
  - ap_mode
  dpt:
  - dbt
  - toff
  hdg:
  - n/a
  - n/a
  - n/a
  - mag_var
  hdm:
  - hdm
  - hdm_true
  rmc:
  - time
  - status
  - position
  - sog
  - tmg
  - date
  - mag_var
  vhm:
  - n/a
  - n/a
  - n/a
  - n/a
  - stw
  vlw:
  - n/a
  - n/a
  - wd
  zda:
  - time
  - day
  - month
  - year
  - tz
variables:
  acir:
  - A
  ap_loran:
  - A
  ap_mode:
  - A
  ap_status:
  - A
  aper:
  - A
  arrival_radius:
  - x.x
  arrived_circle:
  - A
  bdp_true:
  - T
  bearing_origin_to_waypt:
  - x.xT
  - T
  bearing_position_to_waypt:
  - x.xT
  - T
  bearing_to_waypt:
  - x.xT
  - T
  bod:
  - x.x
  bod_true:
  - T
  bpd:
  - x.x
  date:
  - ddmmyy
  day:
  - DD_day
  dbt:
  - x.x
  did:
  - str
  dw:
  - x.x
  hdm:
  - x.x
  hdm_true:
  - T
  hts:
  - x.xT
  - T
  lat:
  - lat
  - lat_NS
  long:
  - long
  - long_WE
  mag_var:
  - x.x
  - w
  month:
  - DD_month
  passed_waypt:
  - A
  position:
  - lat
  - lat_NS
  - pos_long
  - pos_WE
  radius_units:
  - A
  sog:
  - x.x
  status:
  - A
  stw:
  - x.x
  time:
  - hhmmss.ss
  tmg:
  - x.x
  toff:
  - -x.x
  tz:
  - tz_h
  - tz:m
  waypt_id:
  - str
  xte:
  - Lx.xN
  - R
  - "N"
  year:
  - DD_year
