sentences:
  apb:
  - status
  - n/a
  - xte
  - xte_units
  - acir
  - aper
  - bod
  - bod_true
  - did
  - bpd
  - bpd_true
  - hts
  - hts_true
  dpt:
  - dbt
  - toff
  hdg:
  - n/a
  - n/a
  - n/a
  - mag_var
  hdm:
  - hdm
  rmc:
  - time
  - status
  - position
  - sog
  - tmg
  - date
  - mag_var
  vhm:
  - n/a
  - n/a
  - n/a
  - n/a
  - stw
  vlw:
  - n/a
  - n/a
  - wd
  zda:
  - time
  - day
  - month
  - year
  - tz
variables:
  acir:
  - A
  aper:
  - A
  bdp_true:
  - T
  bod:
  - x.x
  bod_true:
  - T
  bpd:
  - x.x
  date:
  - ddmmyy
  day:
  - DD_day
  dbt:
  - x.x
  did:
  - str
  dw:
  - x.x
  hdm:
  - x.x
  hts:
  - x.x
  hts_true:
  - T
  lat:
  - lat
  - lat_NS
  long:
  - long
  - Long_WE
  mag_var:
  - x.x
  - w
  month:
  - DD_month
  position:
  - lat
  - lat_NS
  - pos_long
  - pos_WE
  sog:
  - x.x
  status:
  - A
  stw:
  - x.x
  time:
  - hhmmss.ss
  tmg:
  - x.x
  toff:
  - x.x
  tz:
  - tz_h
  - tz:m
  tzhrs:
  - tz_h
  - tz_m
  xte:
  - x.x
  - R
  xte_units:
  - A
  year:
  - DD_year
